version: "3.1"

volumes:
  db:

services:
  postgres:
    image: postgres:14.1-alpine
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: "host"        
    restart: on-failure
    environment:
     - POSTGRES_PASSWORD=postgres